# Site settings
title: Satheesh Davidson
header: I am Satheesh
email: davidsonsatheesh@gmail.com
url: https://satheeshds.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
#skills: ".NetCore - Cloud - SQL - PostgreSql"
meta_author: Satheesh Davidson

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  dark: 1a242f

# Footer settings
footer:
  copyright: Satheesh Davidson
  location: Contact
  social: Get in touch with me

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/satheeshdavidso
  - title: stack-overflow
    url: https://stackoverflow.com/users/story/6838875
  - title: linkedin
    url: https://www.linkedin.com/in/satheeshds
  - title: github
    url: https://github.com/satheeshds

# Postal address (add as many lines as necessary)
address:
  - line: davisonsatheesh@gmail.com


# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: "posts"
      type: "posts"
    values:
      permalink: ""

#disqus
disqus:
  shortname: satheeshdsgithubpage

